// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: help.sql

package sqlc

import (
	"context"
)

const countHelpMessage = `-- name: CountHelpMessage :one
SELECT COUNT(*) FROM help
`

func (q *Queries) CountHelpMessage(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHelpMessage)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHelpMessage = `-- name: CreateHelpMessage :one
INSERT INTO help (
  fullname,
 email,
  topic,
message
) VALUES (
$1, $2, $3, $4
  )
RETURNING id, fullname, email, topic, message, created_at
`

type CreateHelpMessageParams struct {
	Fullname string `json:"fullname"`
	Email    string `json:"email"`
	Topic    string `json:"topic"`
	Message  string `json:"message"`
}

func (q *Queries) CreateHelpMessage(ctx context.Context, arg CreateHelpMessageParams) (Help, error) {
	row := q.db.QueryRowContext(ctx, createHelpMessage,
		arg.Fullname,
		arg.Email,
		arg.Topic,
		arg.Message,
	)
	var i Help
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.Topic,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHelpMessage = `-- name: DeleteHelpMessage :exec
DELETE FROM help
WHERE id = $1
`

func (q *Queries) DeleteHelpMessage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteHelpMessage, id)
	return err
}

const getHelpMessageByID = `-- name: GetHelpMessageByID :one
SELECT id, fullname, email, topic, message, created_at FROM help
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetHelpMessageByID(ctx context.Context, id int64) (Help, error) {
	row := q.db.QueryRowContext(ctx, getHelpMessageByID, id)
	var i Help
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.Topic,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const listHelpMesage = `-- name: ListHelpMesage :many
SELECT id, fullname, email, topic, message, created_at FROM help
ORDER BY created_at
LIMIT $1
OFFSET $2
`

type ListHelpMesageParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListHelpMesage(ctx context.Context, arg ListHelpMesageParams) ([]Help, error) {
	rows, err := q.db.QueryContext(ctx, listHelpMesage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Help{}
	for rows.Next() {
		var i Help
		if err := rows.Scan(
			&i.ID,
			&i.Fullname,
			&i.Email,
			&i.Topic,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
