// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: product.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM products
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  category_id, 
  name, 
  description, 
  price, 
  stock,
  photo_url
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, category_id, name, description, price, stock, photo_url, created_at, updated_at
`

type CreateProductParams struct {
	CategoryID  int64  `json:"category_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       string `json:"price"`
	Stock       int32  `json:"stock"`
	PhotoUrl    []byte `json:"photo_url"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.PhotoUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products 
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const deleteProductByCategoryID = `-- name: DeleteProductByCategoryID :execrows
DELETE FROM products
WHERE category_id = $1
`

func (q *Queries) DeleteProductByCategoryID(ctx context.Context, categoryID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProductByCategoryID, categoryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProductByCategoryID = `-- name: GetProductByCategoryID :many
SELECT id FROM products
WHERE category_id = $1
`

func (q *Queries) GetProductByCategoryID(ctx context.Context, categoryID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getProductByCategoryID, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, category_id, name, description, price, stock, photo_url, created_at, updated_at FROM products 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTopProducts = `-- name: GetTopProducts :many
SELECT 
  p.id,
  p.name,
  SUM(oi.quantity) AS total_sold,
  SUM(oi.quantity * oi.price) AS total_revenue
FROM products p
JOIN order_items oi ON p.id = oi.product_id
GROUP BY p.id
ORDER BY total_sold DESC
LIMIT 10
`

type GetTopProductsRow struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	TotalSold    int64  `json:"total_sold"`
	TotalRevenue string `json:"total_revenue"`
}

func (q *Queries) GetTopProducts(ctx context.Context) ([]GetTopProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopProductsRow{}
	for rows.Next() {
		var i GetTopProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TotalSold,
			&i.TotalRevenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT 
    id, 
    category_id, 
    name, 
    description, 
    price, 
    stock, 
    photo_url 
FROM products 
WHERE
    CASE WHEN $1::bool THEN category_id = $2 ELSE TRUE END
    AND 
    CASE WHEN $5::bool THEN name ILIKE '%' || $6 || '%' ELSE TRUE END
ORDER BY
    CASE WHEN $7::bool THEN name END ASC,
    CASE WHEN $8::bool THEN name END DESC,
    CASE WHEN $9::bool THEN price END ASC,
    CASE WHEN $10::bool THEN price END DESC,
    id ASC
LIMIT $3
OFFSET $4
`

type ListProductsParams struct {
	Column1    bool           `json:"column_1"`
	CategoryID int64          `json:"category_id"`
	Limit      int64          `json:"limit"`
	Offset     int64          `json:"offset"`
	Column5    bool           `json:"column_5"`
	Column6    sql.NullString `json:"column_6"`
	Column7    bool           `json:"column_7"`
	Column8    bool           `json:"column_8"`
	Column9    bool           `json:"column_9"`
	Column10   bool           `json:"column_10"`
}

type ListProductsRow struct {
	ID          int64  `json:"id"`
	CategoryID  int64  `json:"category_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       string `json:"price"`
	Stock       int32  `json:"stock"`
	PhotoUrl    []byte `json:"photo_url"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProducts,
		arg.Column1,
		arg.CategoryID,
		arg.Limit,
		arg.Offset,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsRow{}
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.PhotoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET 
  category_id = $2,
  name = $3,
  description = $4,
  price = $5,
  stock = $6,
  photo_url = $7,
  updated_at = NOW()
WHERE id = $1
RETURNING id, category_id, name, description, price, stock, photo_url, created_at, updated_at
`

type UpdateProductParams struct {
	ID          int64  `json:"id"`
	CategoryID  int64  `json:"category_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       string `json:"price"`
	Stock       int32  `json:"stock"`
	PhotoUrl    []byte `json:"photo_url"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.PhotoUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
